### ISSUE TITLE
#rx-y (where X and Y are numbers and u select a random number on that range) on AFB stopped working

### ISSUE THREAD

**Issue by cscarlet** [Zode/AFBase#4]
Someone has reported random number values have stopped working since 5.13, since its not Sven related thought best to log issue on Github:

#rx-y (where X and Y are numbers and u select a random number on that range) on AFB stopped working
When doing classify #r0-14 it'd always select 0 only

I have asked if there is any server logs in case any errors are trapped.

**Comment by Zode** [comment]
i mean, if he inputted #r0-14 it will end up in 0 because that is not the syntax and it tries to parse it as a value, the correct syntax is: r#0-14
though, this no longer works in 1.6.0 and should be formatted as: r#0#14
this is to allow for negative numbers to be used eg. r#-10#10

**Comment by cscarlet** [comment]
Ops that might have been me mis-reading, I'll double check

**Comment by cscarlet** [comment]
Nope apologises it was incorrect syntax
